### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by DmitryZhyvoder** [RDmitriev/Droid.engine#1]
Здравствуйте Руслан. Мне достался проект, сделанный на Вашем движке довольно старой версии. Думаю обновить, но не пойму как. Какова процедура? Нужно ли чтото делать с базой, или достаточно заменить файлы? В старой версии есть фал настроек подключения к базе, в новой - нет, как быть? Може есть смысл сделать описание?

**Comment by RDmitriev** [comment]
Здравствуйте, автоматического обновления в данный момент нет.
Скажите название сайта, думаю мы этот сайт и делали, посмотрю насколько он стар.
Новый файл конфигурации генерируется на автомате при чистой установке.

**Comment by DmitryZhyvoder** [comment]
printfoto.org

**Comment by DmitryZhyvoder** [comment]
Да, он суперстар - версия 0.13

**Comment by RDmitriev** [comment]
Учет в changelog.txt я на время перестал вести, так что версия не такая уж и старая.

Что бы было проще обновить ставим новую версию,
закачиваем туда папку /upload с картинками
в базе удаляем таблицу droid_structure (лучше изменить старую, так как товаров на принтфото куча)
заливаем в место нее старую таблицу putto_structure
переименовываем в droid_structure

и осталось только изменить ссылки на картинки, прописать старые пути в файлах:
/droid/app/content/page.html
/droid/app/content/product.html

**Comment by DmitryZhyvoder** [comment]
ок, спасибо

**Comment by DmitryZhyvoder** [comment]
Здравствуйте Руслан!

Сделал как Вы сказали - установил заново, база другая
сделал экспорт структурры putto d cnfhjq ,fpt
удалил в новой структу droid
все вхождения в бекапе putto_structure заменил на droid_structure
импортировал структура в новую базу

пути в файлах page и продукт не изменил, где менять? папка upload осталась тамже где и была
тут бекап старой папки со скрипами https://yadi.sk/d/eoWhzDEbhF5qk

Пожалйста, помогите обновить.

Спасибо, 
Дмитрий

**Comment by DmitryZhyvoder** [comment]
откатил изменения назад, больше ждать не можем.

**Comment by RDmitriev** [comment]
А чем не устраивает версия на котором стоит сейчас сайт? Она вполне стабильна.

**Comment by DmitryZhyvoder** [comment]
Мы надеемся, что Вы устраняете ошибки, если находите.

**Comment by RDmitriev** [comment]
Да если есть ошибки, я устраняю их сразу. Если, что найдете пишите.
